services:
    postgresdb:
        image: postgres:17
        port:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgresDb
        volumes:
            - "postgres_data:/var/lib/postgresql/data"

volumes:
    postgres_data:
